name: Setup SSH
description: Кладёт приватный ключ и добавляет хост в known_hosts
inputs:
  ssh-private-key:
    required: true
  host:
    required: true
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        mkdir -p ~/.ssh
        cat << 'EOF' > ~/.ssh/id_rsa
        ${{ inputs.ssh-private-key }}
        EOF
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H "${{ inputs.host }}" >> ~/.ssh/known_hosts
