name: Setup Ansible
description: Ставит ansible, community.general и кладёт .vault_pass
inputs:
  vault-password:
    required: true
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        sudo apt-get update -y
        sudo apt-get install -y ansible
        ansible-galaxy collection install community.general

    - shell: bash
      run: |
        echo "${{ inputs.vault-password }}" > .vault_pass
        chmod 600 .vault_pass
