name: Deploy to VPS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible
          ansible --version

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 62.182.102.68 >> ~/.ssh/known_hosts

      - name: Run Ansible playbook
        run: |
          echo "${{ secrets.VAULT_PASS }}" | ansible-playbook \
            -i deploy/ansible/inventory.yml \
            deploy/ansible/playbook.yml \
            --vault-password-file /dev/stdin \
            -vv
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"